(()=>{
'use strict';
const $=id=>document.getElementById(id), E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v??'').replace(/\D/g,'');
const norm755=v=>String(v??'').normalize('NFKC').replace(/\uFFFD/g,' ').toLowerCase().replace(/[^0-9a-z가-힣]/g,'');
function phoneIssue(c){const p=digits(c?.phone);if(!p)return '연락처 없음';if(!/^01\d{8,9}$/.test(p))return `연락처 확인 (${c?.phone||''})`;return ''}
function customerIssues(c){const a=[];if(!String(c?.name||'').trim())a.push('실명 없음');if(!String(c?.nickname||c?.nick||'').trim())a.push('닉네임 없음');const p=phoneIssue(c);if(p)a.push(p);if(!String(c?.address||'').trim())a.push('주소 없음');return a}
function injectCustomerIssueBox(){const table=$('customersTable');if(!table||$('v755CustomerIssues'))return;const card=document.createElement('div');card.id='v755CustomerIssues';card.className='card v755-issue-card';card.innerHTML='<div class="section-title" style="margin-top:0"><h3>⚠️ 정보수정 필요 고객</h3><div class="actions"><button class="btn secondary" onclick="renderCustomerIssuesV755()">새로고침</button></div></div><div id="v755IssueSummary" class="muted"></div><div id="v755IssueList"></div>';table.parentNode.insertBefore(card,table);renderCustomerIssuesV755()}
window.renderCustomerIssuesV755=()=>{const list=(state.customers||[]).map((c,i)=>({c,i,issues:customerIssues(c)})).filter(x=>x.issues.length);const s=$('v755IssueSummary'),b=$('v755IssueList');if(!s||!b)return;s.innerHTML=`전체 ${state.customers?.length||0}명 중 <span class="v755-issue-badge">수정 필요 ${list.length}명</span>`;b.innerHTML=list.length?`<div class="scroll"><table><thead><tr><th>이름</th><th>닉네임</th><th>연락처</th><th>문제</th><th>바로수정</th></tr></thead><tbody>${list.map(x=>`<tr><td>${E(x.c.name||'-')}</td><td>${E(x.c.nickname||x.c.nick||'-')}</td><td class="${phoneIssue(x.c)?'v755-badphone':''}">${E(x.c.phone||'-')}</td><td class="v755-missing">${E(x.issues.join(' · '))}</td><td><button class="btn" onclick="editCustomer(${x.i})">수정</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="muted" style="padding:10px">현재 정보수정 필요 고객이 없습니다.</div>'};
const oldRenderCustomers=window.renderCustomers;
if(typeof oldRenderCustomers==='function')window.renderCustomers=function(){const y=scrollY;oldRenderCustomers();injectCustomerIssueBox();renderCustomerIssuesV755();requestAnimationFrame(()=>scrollTo({top:y,behavior:'auto'}))};

/* packing rule inference from product text. Manual rules are never overwritten. */
function inferRule(item,number){const s=String(item||'').normalize('NFKC');let m=s.match(/1\s*세트\s*(?:=|:|x|×|\*)?\s*(\d+)\s*(개|켤레|봉지|봉|팩|박스|묶음)/i);if(m)return {number,saleUnit:'세트',componentQty:+m[1],componentUnit:m[2],actualUnit:m[2],source:'auto'};m=s.match(/(\d+)\s*(개|켤레|봉지|봉|팩|박스)\s*(?:=|:)?\s*1\s*세트/i);if(m)return {number,saleUnit:'세트',componentQty:+m[1],componentUnit:m[2],actualUnit:m[2],source:'auto'};m=s.match(/(\d+)\s*(켤레|개|봉지|봉|팩|박스)\s*1\s*묶음\s*1\s*세트/i);if(m)return {number,saleUnit:'세트',componentQty:+m[1],componentUnit:m[2],actualUnit:'묶음',actualPerSale:1,source:'auto'};return null}
window.inferPackingRulesV755=()=>{state.packingRules=state.packingRules||{};let n=0;for(const o of (state.orders||[])){const no=String(o.number||'').replace(/^#/,'').trim();if(!no||state.packingRules[no])continue;const r=inferRule(o.item,no);if(r){r.productName=o.item;r.updatedAt=new Date().toISOString();state.packingRules[no]=r;n++}}if(n){try{saveSilently()}catch(e){}window.renderPackingRulesV750?.()}return n};
['orderFile','quickOrderFile'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(()=>{const n=inferPackingRulesV755();if(n)console.log('포장규칙 자동감지',n)},900)));

/* More tolerant deposit name and amount matching */
function tokens755(v){const raw=String(v??'').normalize('NFKC').replace(/\uFFFD/g,' ').trim();const out=new Set();const add=x=>{const n=norm755(x);if(n)out.add(n)};add(raw);for(const m of raw.matchAll(/[\(（\[【]([^\)）\]】]+)[\)）\]】]/g))add(m[1]);add(raw.replace(/[\(（\[【].*?[\)）\]】]/g,' '));raw.split(/[\s,\/|·ㆍ:;\-]+/).forEach(add);return out}
function payerMatch755(payer,toks){const p=tokens755(payer),full=norm755(payer);for(const t of p)if(toks.has(t))return true;for(const t of toks)if(t.length>=2&&(full.includes(t)||t.includes(full)))return true;return false}
function amt755(v){let s=String(v??'').normalize('NFKC').replace(/,/g,'').replace(/원/g,'').trim();const neg=/^-|출금|취소/.test(s);const n=Math.round(Math.abs(Number(s.replace(/[^0-9.]/g,''))||0));return neg?-n:n}
const oldGet=window.getReceipts;
if(typeof oldGet==='function')window.getReceipts=function(){const groups=new Map();(state.orders||[]).forEach(o=>{const k=o.date+'|'+norm755(o.nick);if(!groups.has(k))groups.set(k,{key:k,date:o.date,nick:o.nick,items:[],customerId:o.customerId,matchStatus:o.matchStatus,fee:Number(o.fee)||0});groups.get(k).items.push(o)});const rs=[...groups.values()].map(g=>{let c=(state.customers||[]).find(x=>x.id===g.customerId)||null;if(!c&&typeof findCustomerByNick==='function'){const mm=findCustomerByNick(g.nick);c=mm.customer||null;if(c){g.customerId=c.id;g.matchStatus=mm.status}}const subtotal=g.items.reduce((a,x)=>a+(Number(x.amount)||0),0),total=subtotal+(Number(g.fee)||0);return {...g,customer:c,subtotal,total,starred:g.items.some(x=>x.starred)}});const used=new Set();for(const r of rs){const ov=state.paymentOverrides?.[r.key];if(ov?.status){r.payment={status:ov.status,payment:ov.payment||null,manual:true,verified:ov.status==='paid',reason:'관리자 수기변경'};continue}const toks=new Set();[r.nick,r.customer?.name,r.customer?.nick,r.customer?.nickname,r.customer?.paymentName,r.customer?.depositor].filter(Boolean).forEach(v=>tokens755(v).forEach(t=>toks.add(t)));const named=(state.payments||[]).map((p,i)=>({p,i})).filter(x=>payerMatch755(x.p.payer,toks)&&!used.has(x.i));const exact=named.filter(x=>amt755(x.p.amount)===amt755(r.total));if(exact.length===1){used.add(exact[0].i);r.payment={status:'paid',payment:exact[0].p,verified:true,reason:'본명/닉네임/괄호명 + 금액 정확히 일치'};continue}if(exact.length>1){r.payment={status:'review',payment:exact[0].p,verified:false,reason:'같은 이름/금액 입금이 여러 건'};continue}if(named.length){const closest=[...named].sort((a,b)=>Math.abs(amt755(a.p.amount)-amt755(r.total))-Math.abs(amt755(b.p.amount)-amt755(r.total)))[0];r.payment={status:'amount-mismatch',payment:closest.p,verified:false,reason:`이름 일치 · 청구 ${amt755(r.total).toLocaleString()} / 입금 ${amt755(closest.p.amount).toLocaleString()}`}}else r.payment={status:'unpaid',payment:null,verified:false}}return rs.sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.nick).localeCompare(String(b.nick),'ko'))};

/* Receipt selection: select visible rows reliably */
window.toggleAllReceiptPrintV747=v=>{const boxes=[...document.querySelectorAll('#receiptCards input.v7474-receipt-check,#receiptCards input.v747-receipt-check')];boxes.forEach(cb=>{cb.checked=v;cb.dispatchEvent(new Event('change',{bubbles:true}))});};
window.toggleAllShippingPrintV747=v=>{const boxes=[...document.querySelectorAll('#shippingTable input.v7474-ship-check,#shippingTable input.v747-ship-check,.v755-ship-check')];boxes.forEach(cb=>{cb.checked=v;cb.dispatchEvent(new Event('change',{bubbles:true}))});};

function optionText755(item){const s=String(item||'');const vals=[];for(const m of s.matchAll(/[\(（]([^\)）]+)[\)）]/g))vals.push(m[1]);if(s.includes('/'))vals.push(...s.split('/').slice(1).map(x=>x.trim()));const known=s.match(/(?:사이즈|색상|컬러|향|맛)\s*[:：]?\s*([^,|/]+)/gi)||[];vals.push(...known);return [...new Set(vals.filter(Boolean))].join(' / ')||'-'}
function calc755(x){if(typeof window.packCalcV750==='function')return window.packCalcV750(x);return {actualQty:Number(x.qty)||0,actualUnit:'개',orderQty:Number(x.qty)||0,saleUnit:'개',componentQty:1,componentUnit:'개'}}
function shipCode755(g){return typeof shippingCodeFor==='function'?shippingCodeFor(g):norm755([g.name,g.nick,g.phone,g.address].join('|'))}
window.renderShipping=function(){const filter=$('shippingFilter')?.value||'paid',bundle=$('bundleMode')?.value||'date';let rs=getReceipts();if(filter==='paid')rs=rs.filter(r=>r.payment?.status==='paid');const groups=new Map();rs.forEach(r=>{const c=r.customer||{},k=bundle==='customer'?(c.id||r.nick):r.key;if(!groups.has(k))groups.set(k,{key:r.key,name:c.name||'',nick:r.nick,phone:c.phone||'',postalCode:c.postalCode||'',address:[c.address,c.detailAddress].filter(Boolean).join(' '),memo:c.memo||'',dates:new Set(),items:[],subtotal:0,fee:0,total:0,status:r.payment?.status||'unpaid'});const g=groups.get(k);g.dates.add(r.date);g.items.push(...r.items.map(x=>({...x})));g.subtotal+=Number(r.subtotal)||0;g.fee+=Number(r.fee)||0;g.total+=Number(r.total)||0});const arr=[...groups.values()].map(g=>({...g,code:shipCode755(g)}));window.currentShipping=arr;state.shippingScans=state.shippingScans||{};const box=$('shippingTable');if(!box)return;box.innerHTML=arr.length?`<div class="scroll"><table class="v755-ship-table"><thead><tr><th><input type="checkbox" onchange="toggleAllShippingPrintV747(this.checked)"></th><th>상태</th><th>고객</th><th>연락처/주소</th><th>상품·옵션·실제 포장수량</th><th>금액</th><th>송장</th><th>관리</th></tr></thead><tbody>${arr.map(g=>{const s=state.shippingScans[g.code]||{},checks=s.itemChecks||{},short=Object.values(checks).some(x=>x?.shortage);return `<tr><td><input type="checkbox" class="v755-ship-check" data-code="${E(g.code)}"></td><td>${s.shipmentScanAt?'🚚 출고준비완료':s.at?'🟢 포장완료':'⏳ 포장대기'}${short?'<div class="v755-shortage">⚠️ 재고부족</div>':''}<br><small>${E(s.worker||'')}</small></td><td><b>${E(g.name||g.nick)}</b><br>${E(g.nick)}<br><small>${[...g.dates].join(', ')}</small></td><td>${E(g.phone)}<br><span class="address-cell">${E(g.address)}</span></td><td class="ship-items">${g.items.map((x,i)=>{const c=calc755(x),opt=optionText755(x.item);return `<div><b>#${E(x.number||i+1)} ${E(x.item)}</b>${opt!=='-'?` <span class="v755-option">[${E(opt)}]</span>`:''}<br><span class="v755-actual">📦 ${c.actualQty}${E(c.actualUnit)} 넣기</span> <small>(${c.orderQty}${E(c.saleUnit)}${c.componentQty>1?` · 1${E(c.saleUnit)}=${c.componentQty}${E(c.componentUnit)}`:''})</small></div>`}).join('<hr>')}</td><td>상품 ${Number(g.subtotal).toLocaleString()}원<br>배송비 ${Number(g.fee).toLocaleString()}원<br><b>총 ${Number(g.total).toLocaleString()}원</b></td><td>${E(s.courier||'CJ대한통운')}<br><b>${E(s.trackingNumber||'-')}</b><br>${s.deliverySmsError?'<span class="v755-shortage">문자실패</span>':s.deliverySmsSentAt?'문자완료':''}</td><td><button class="btn secondary" onclick="openReceiptDetail('${E(g.key)}')">정산서 보기/수정</button>${s.deliverySmsError?` <button class="btn" onclick="resendDeliverySmsV749?.('${E(g.code)}',this)">배송문자 재발송</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">출력할 택배 대상이 없습니다.</div>';};

function ensureShipButtons(){const h=document.querySelector('#shipping .section-title .actions');if(!h||$('v755PrintAll'))return;const b=document.createElement('button');b.id='v755PrintAll';b.className='btn';b.textContent='전체 택배리스트 인쇄';b.onclick=()=>{renderShipping();window.printShipping?.()};h.prepend(b)}

/* Kimchi list: summary + who ordered */
window.printKimchiListV748=async()=>{renderShipping();const arr=(window.currentShipping||[]).map(g=>({...g,items:(g.items||[]).filter(x=>/(김치|깍두기|총각|열무|배추|파김치|갓김치|백김치|동치미|겉절이)/i.test(String(x.item||'')))})).filter(g=>g.items.length);if(!arr.length)return alert('김치 주문이 없습니다.');const mp=new Map();arr.forEach(g=>g.items.forEach(x=>{const c=calc755(x),key=[x.number,x.item,optionText755(x.item),c.actualUnit].join('|');if(!mp.has(key))mp.set(key,{number:x.number,item:x.item,opt:optionText755(x.item),qty:0,unit:c.actualUnit,customers:[]});const z=mp.get(key);z.qty+=c.actualQty;z.customers.push(`${g.name||g.nick}(${g.nick}) ${c.actualQty}${c.actualUnit}`)}));const rows=[...mp.values()];const company=window.__tenantCompany||'땡라이브';const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,'Noto Sans KR',sans-serif;padding:24px}h1{color:#e65f00}table{width:100%;border-collapse:collapse;margin:14px 0 28px}th,td{border:1px solid #999;padding:9px}th{background:#fff0e0}.qty{font-size:20px;font-weight:900;color:#d44}.customer{line-height:1.65}@media print{button{display:none}}</style></head><body><h1>🥬 ${E(company)} 김치 준비 총괄표</h1><table><thead><tr><th>#</th><th>김치/옵션</th><th>총 포장수량</th><th>주문 고객</th></tr></thead><tbody>${rows.map(r=>`<tr><td>#${E(r.number)}</td><td>${E(r.item)}<br>${E(r.opt)}</td><td class="qty">${r.qty}${E(r.unit)}</td><td class="customer">${r.customers.map(E).join('<br>')}</td></tr>`).join('')}</tbody></table><h2>고객별 김치 주문</h2>${arr.map(g=>`<section><h3>${E(g.name||g.nick)} / ${E(g.nick)}</h3><ul>${g.items.map(x=>{const c=calc755(x);return `<li>#${E(x.number)} ${E(x.item)} → <b>${c.actualQty}${E(c.actualUnit)}</b></li>`}).join('')}</ul></section>`).join('')}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};

/* SMS/MMS image preview confirmation */
const originalSendMms=window.sendMmsByKey;
if(typeof originalSendMms==='function')window.sendMmsByKey=async function(key,button,skipConfirm=false){if(skipConfirm)return originalSendMms(key,button,true);const r=getReceipts().find(x=>x.key===key);if(!r||!r.customer?.phone)return alert('고객 연락처가 없습니다.');let img='';try{img=await receiptImageBase64(r)}catch(e){return alert('정산서 미리보기 생성 실패: '+e.message)}const back=document.createElement('div');back.className='v755-preview-back';back.innerHTML=`<div class="v755-preview"><h2>문자 전송 전 확인</h2><p><b>${E(r.customer.name||r.nick)}</b> · ${E(r.customer.phone)}<br>정산서 이미지와 문자 내용을 확인한 뒤 전송하세요.</p><img src="data:image/jpeg;base64,${img}"><div class="v755-preview-actions"><button class="btn secondary" id="v755Cancel">취소</button><button class="btn" id="v755Send">이대로 전송할까요? 전송</button></div></div>`;document.body.appendChild(back);return new Promise(resolve=>{back.querySelector('#v755Cancel').onclick=()=>{back.remove();resolve(false)};back.querySelector('#v755Send').onclick=async()=>{back.remove();try{const ok=await originalSendMms(key,button,true);resolve(ok)}catch(e){alert(e.message);resolve(false)}}})};

/* archive receipts in date records */
function archivedReceipts755(st){if(!st)return[];const cs=st.customers||[],mp=new Map();(st.orders||[]).forEach(o=>{const k=o.date+'|'+norm755(o.nick);if(!mp.has(k))mp.set(k,{date:o.date,nick:o.nick,items:[],customerId:o.customerId,fee:Number(o.fee)||0});mp.get(k).items.push(o)});return [...mp.values()].map(g=>{const c=cs.find(x=>x.id===g.customerId)||{};const sub=g.items.reduce((a,x)=>a+(Number(x.amount)||0),0);return {...g,customer:c,subtotal:sub,total:sub+g.fee}})}
const oldLoadRecords=window.loadRecordsV747;
if(typeof oldLoadRecords==='function')window.loadRecordsV747=async function(){await oldLoadRecords();const d=$('recordDate')?.value;if(!d)return;try{const a=await fetch('/api/archive?date='+encodeURIComponent(d),{cache:'no-store'}).then(r=>r.json());const st=a.archive?.state||a.state;let box=$('v755ArchiveReceipts');if(!box){box=document.createElement('div');box.id='v755ArchiveReceipts';box.className='card';$('archiveSummary')?.insertAdjacentElement('afterend',box)}const rs=archivedReceipts755(st);box.innerHTML=`<h3>${E(d)} 정산서 보관함 (${rs.length}명)</h3>${rs.length?`<div class="scroll"><table class="v755-archive-table"><thead><tr><th>닉네임</th><th>이름</th><th>연락처</th><th>상품수</th><th>상품합계</th><th>배송비</th><th>총액</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${E(r.nick)}</td><td>${E(r.customer.name||'-')}</td><td>${E(r.customer.phone||'-')}</td><td>${r.items.length}</td><td>${r.subtotal.toLocaleString()}원</td><td>${r.fee.toLocaleString()}원</td><td><b>${r.total.toLocaleString()}원</b></td></tr>`).join('')}</tbody></table></div>`:'저장된 정산서가 없습니다.'}`;}catch(e){console.warn(e)}};

/* Courier export address sanitizer: postal code never prepended */
const oldDownloadShip=window.downloadShippingList;
window.downloadShippingList=()=>{renderShipping();const strip=(a,p)=>{let s=String(a||'').trim();const pc=String(p||'').replace(/\D/g,'');if(pc&&s.replace(/[-\s]/g,'').startsWith(pc))s=s.replace(new RegExp('^\\s*'+pc.slice(0,3)+'[-\\s]*'+pc.slice(3)+'\\s*'),'');s=s.replace(/^\s*\d{5}\s+/,'');return s.trim()};const rows=(window.currentShipping||[]).map((g,i)=>({'번호':i+1,'포장상태':state.shippingScans?.[g.code]?.shipmentScanAt?'출고준비완료':state.shippingScans?.[g.code]?.at?'포장완료':'대기','택배코드':g.code,'받는분':g.name,'닉네임':g.nick,'연락처':g.phone,'우편번호':g.postalCode||'','주소':strip(g.address,g.postalCode),'상품내역':g.items.map((x,j)=>{const c=calc755(x);return `#${x.number||j+1} ${x.item} / 실제 ${c.actualQty}${c.actualUnit}`}).join(' / '),'상품합계':g.subtotal,'배송비':g.fee,'토탈금액':g.total}));if(typeof exportXlsx==='function')exportXlsx(rows,'FIRST_OMS_택배리스트.xlsx','택배리스트');else oldDownloadShip?.()};

function boot(){injectCustomerIssueBox();ensureShipButtons();inferPackingRulesV755();window.renderPackingRulesV750?.();if($('recordDate')&&!$('recordDate').value)$('recordDate').value=new Date().toLocaleDateString('en-CA');}
window.addEventListener('load',()=>setTimeout(boot,300));
})();
