(()=>{
'use strict';
const $760=id=>document.getElementById(id);
const norm760=v=>String(v??'').replace(/[^0-9a-zA-Z가-힣]/g,'').toLowerCase();
const phone760=v=>String(v??'').replace(/\D/g,'').slice(-11);
function header760(headers,aliases){const ns=headers.map(norm760);for(const a of aliases){const i=ns.findIndex(x=>x.includes(norm760(a)));if(i>=0)return headers[i]}return null}
function read760(buf){const wb=XLSX.read(buf,{type:'array',cellDates:true}),n=wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:'',raw:false})}
function match760(row,groups,headers){const ht=header760(headers,['송장번호','운송장번호','등기번호','tracking']),ho=header760(headers,['주문번호','관리번호','고객번호','택배코드']),hp=header760(headers,['전화번호','휴대폰','연락처','수하인전화']),hn=header760(headers,['받는분','수하인','수취인','고객명','성명','이름']),ha=header760(headers,['주소','배송지']);const tracking=ht?String(row[ht]||'').replace(/\s+/g,'').trim():'';if(!tracking)return {status:'skip',reason:'송장번호 없음'};let c=[];if(ho&&row[ho])c=groups.filter(g=>norm760(g.code)===norm760(row[ho]));if(!c.length&&hp&&row[hp])c=groups.filter(g=>phone760(g.phone)===phone760(row[hp]));if(!c.length&&hn&&ha&&row[hn]&&row[ha])c=groups.filter(g=>(norm760(g.name||g.nick)===norm760(row[hn])||norm760(g.nick)===norm760(row[hn]))&&norm760(g.address).includes(norm760(row[ha]).slice(0,10)));if(!c.length&&hn&&row[hn])c=groups.filter(g=>norm760(g.name||g.nick)===norm760(row[hn])||norm760(g.nick)===norm760(row[hn]));if(c.length===1)return {status:'matched',g:c[0],tracking};if(c.length>1)return {status:'conflict',tracking,reason:'동명이인/중복 고객 — 자동반영 안함'};return {status:'unmatched',tracking,reason:'고객 불일치'}}
async function trackingFile760(e){const f=e.target.files?.[0];if(!f)return;const st=$760('trackingUploadStatus');if(st){st.style.display='block';st.textContent='고객 송장 엑셀을 대조·저장하는 중입니다...'}try{renderShipping();const groups=[...(window.currentShipping||[])],rows=read760(await f.arrayBuffer());if(!rows.length)throw new Error('송장 파일에 데이터가 없습니다.');const headers=Object.keys(rows[0]),updates=[],issues=[];for(const row of rows){const m=match760(row,groups,headers);if(m.status==='matched')updates.push({code:m.g.code,trackingNumber:m.tracking,courier:state.settings?.courier?.company||'CJ대한통운',name:m.g.name||'',nick:m.g.nick||'',phone:m.g.phone||'',address:m.g.address||''});else if(m.status!=='skip')issues.push(`${m.tracking||'-'}: ${m.reason}`)}if(!updates.length)throw new Error('자동으로 대조된 고객 송장이 없습니다. 이름·연락처·주소 열을 확인해 주세요.');const date=(typeof dayv==='function'?dayv():new Date().toISOString().slice(0,10));const r=await fetch('/api/packing/tracking/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,filename:f.name,courier:state.settings?.courier?.company||'CJ대한통운',updates,issues})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'서버 저장 실패');if(typeof syncPackingScans==='function')await syncPackingScans();else{state.shippingScans=state.shippingScans||{};for(const u of updates)state.shippingScans[u.code]={...(state.shippingScans[u.code]||{}),trackingNumber:u.trackingNumber,courier:u.courier,trackingSource:'file-upload'}}renderShipping();if(st)st.innerHTML=`<b>${date} 고객 송장 저장완료</b> · 자동대조 ${d.updated}건 · 보존/건너뜀 ${d.skipped}건 · 확인필요 ${issues.length}건<br><small>${f.name}</small>${issues.length?`<div style="margin-top:8px;color:#b42318">${issues.slice(0,15).map(x=>String(x).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))).join('<br>')}</div>`:''}`;alert(`${date} 고객 송장 저장완료\n자동대조 ${d.updated}건\n확인필요 ${issues.length}건\n\n택배팀은 포장완료 후 고객 송장번호를 자동으로 보게 됩니다.`)}catch(err){if(st)st.textContent='송장파일 업로드 실패: '+err.message;alert('송장파일 업로드 실패: '+err.message)}finally{e.target.value=''}}
document.addEventListener('change',e=>{if(e.target?.id==='trackingFile'){e.stopImmediatePropagation();trackingFile760(e)}},true);
})();
